import React from 'react';
import ReactDOM from 'react-dom';
import Approot from './env/root';
import {sagaMiddleware} from './env/store';
import rootSaga from './sagas';
// import testdata from './sagas/catlfull_mapcitystat_data.json';
// import {setdata} from './sagas/catlfull_mapcitystat_data.js';
// import registerServiceWorker from './registerServiceWorker';
import injectTapEventPlugin from 'react-tap-event-plugin';
injectTapEventPlugin();
sagaMiddleware.run(rootSaga);
ReactDOM.render(<Approot />, document.getElementById('root'));
// registerServiceWorker();
// setdata(testdata);
